// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2sVFCO4FR5dA_zW3QTWuu1FZkehqH_qM',
    appId: '1:71786760529:web:2792f523a47bfec4952b70',
    messagingSenderId: '71786760529',
    projectId: 'agripy-b5422',
    authDomain: 'agripy-b5422.firebaseapp.com',
    storageBucket: 'agripy-b5422.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJKxUTYw3PaUcBB5Nv4JzyGwV7ZR0F-Ic',
    appId: '1:71786760529:android:13cb9e3edd395f51952b70',
    messagingSenderId: '71786760529',
    projectId: 'agripy-b5422',
    storageBucket: 'agripy-b5422.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPL9V9aPdfNWlg6eJWZIYhEj_CZvNUq4Q',
    appId: '1:71786760529:ios:8dda57e93b5456ad952b70',
    messagingSenderId: '71786760529',
    projectId: 'agripy-b5422',
    storageBucket: 'agripy-b5422.firebasestorage.app',
    iosClientId: '71786760529-q1eoc34l3r519r45gueem9eq1hopucvo.apps.googleusercontent.com',
    iosBundleId: 'com.example.agripy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPL9V9aPdfNWlg6eJWZIYhEj_CZvNUq4Q',
    appId: '1:71786760529:ios:8dda57e93b5456ad952b70',
    messagingSenderId: '71786760529',
    projectId: 'agripy-b5422',
    storageBucket: 'agripy-b5422.firebasestorage.app',
    iosClientId: '71786760529-q1eoc34l3r519r45gueem9eq1hopucvo.apps.googleusercontent.com',
    iosBundleId: 'com.example.agripy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2sVFCO4FR5dA_zW3QTWuu1FZkehqH_qM',
    appId: '1:71786760529:web:54b811b7c82ebbc1952b70',
    messagingSenderId: '71786760529',
    projectId: 'agripy-b5422',
    authDomain: 'agripy-b5422.firebaseapp.com',
    storageBucket: 'agripy-b5422.firebasestorage.app',
  );

}